"""Add reset_token and reset_token_exp to users

Revision ID: e42c81a79c34
Revises: 9ff8a0824cfd
Create Date: 2025-12-15 13:48:36.136273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42c81a79c34'
down_revision = '9ff8a0824cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_exp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_exp')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
